---
- name: Deploy webapp       
  hosts: ICTSemAppServer
  become: True
  tasks:
   - name: Stop Container
     command: docker stop webapp
     ignore_errors: yes

   - name: Remove Container
     command: docker rm webapp
     ignore_errors: yes

   - name: Remove Image       
     command: docker rmi tutordevops-img
     ignore_errors: yes

   - name: Build Container  
     command: docker build -t tutordevops-img .
     args:
       chdir: /home/docker-admin

   - name: Start Container         
     command: docker run -d --name tutordevops -p 8080:8080 tutordevops-img
